acme_payment_homepage:
    pattern:  /payment
    defaults: { _controller: AcmePaymentBundle:Default:index }

acme_payment_prepare_simple_purchase_authorize_net:
    pattern:  /payment/simple_purchase/authorize_net/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchaseAuthorizeNetAim:prepare }
    
acme_payment_prepare_simple_purchase_be2bill:
    pattern:  /payment/simple_purchase/be2bill/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchaseBe2Bill:prepare }
    
acme_payment_prepare_simple_purchase_paypal_express_via_omnipay:
    pattern:  /payment/simple_purchase/paypal_express_via_omnipay/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalExpressViaOmnipay:prepare }

acme_payment_prepare_simple_purchase_stripe_via_omnipay:
    pattern:  /payment/simple_purchase/stripe_via_omnipay/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchaseStripeViaOmnipay:prepare }

acme_payment_prepare_simple_purchase_paypal_pro:
    pattern:  /payment/simple_purchase/paypal_express_pro/prepare
    defaults: { _controller: AcmePaymentBundle:SimplePurchasePaypalPro:prepare }

acme_payment_details_view:
    pattern:  /payment/details
    defaults: { _controller: AcmePaymentBundle:Details:view }
    
acme_payment_notifications_list:
    pattern:  /payment/notifications/list
    defaults: { _controller: AcmePaymentBundle:Notifications:list }