imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
        mappings:
            payum:
                is_bundle: false
                type: xml
                dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Bridge/Doctrine/Resources/mapping
                prefix: Payum\Bridge\Doctrine\Entity                
            payum_paypal_express_checkout_nvp:
                is_bundle: false
                type: xml 
                dir: %kernel.root_dir%/../vendor/payum/paypal-express-checkout-nvp/src/Payum/Paypal/ExpressCheckout/Nvp/Bridge/Doctrine/Resources/mapping
                prefix: Payum\Paypal\ExpressCheckout\Nvp\Bridge\Doctrine\Entity

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_payment_core:
    secret:                                               %kernel.secret%

jms_payment_paypal:
    username:                                             %paypal.express_checkout.username%
    password:                                             %paypal.express_checkout.password%
    signature:                                            %paypal.express_checkout.signature%
    debug:                                                true
    
payum:
    contexts:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true
                        
                actions:
                    - acme.payment.payum.action.store_notification

            storages:
                Acme\PaypalExpressCheckoutBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                        
        paypal_express_checkout_plus_doctrine:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaypalExpressCheckoutBundle\Entity\PaymentDetails:
                    doctrine:
                        driver: orm
                        payment_extension: true
                Acme\PaymentBundle\Entity\TokenizedDetails:
                    doctrine:
                        driver: orm
                        payment_extension: true
                        
        paypal_express_checkout_recurring_payment:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaypalExpressCheckoutBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaypalExpressCheckoutBundle\Model\RecurringPaymentDetails:
                      filesystem:
                          storage_dir: %kernel.root_dir%/Resources/payments
                          id_property: id
                          payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                        
        paypal_express_checkout_recurring_payment_plus_doctrine:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            storages:
                Acme\PaypalExpressCheckoutBundle\Entity\PaymentDetails:
                    doctrine:
                        driver: orm
                        payment_extension: true
                Acme\PaymentBundle\Entity\TokenizedDetails:
                    doctrine:
                        driver: orm
                        payment_extension: true
                Acme\PaypalExpressCheckoutBundle\Entity\RecurringPaymentDetails:
                    doctrine:
                        driver: orm
                        payment_extension: true

        paypal_pro_checkout:
            paypal_pro_checkout_nvp:
                api:
                    options:
                        username: %paypal.pro_checkout.username%
                        password: %paypal.pro_checkout.password%
                        partner:  %paypal.pro_checkout.partner%
                        vendor:   %paypal.pro_checkout.vendor%
                        sandbox: true
            storages:
                Acme\PaymentBundle\Model\PaypalProPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                
        authorize_net:
            authorize_net_aim:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true
            storages:
                Acme\PaymentBundle\Model\AuthorizeNetPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true

        be2bill:
            be2bill:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            storages:
                Acme\PaymentBundle\Model\Be2BillPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                
        paypal_express_checkout_via_ominpay:
            omnipay:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true
                    
            storages:
                Acme\PaymentBundle\Model\OmnipayPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true

        payex:
            payex:
                api:
                    options:
                        account_number:  %payex.account_number%
                        encryption_key:  %payex.encryption_key%
                        sandbox: true
                actions:
                    - acme.payex.payum.action.store_notification
            storages:
                Acme\PayexBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                        
        payex_agreement:
            payex:
                api:
                    options:
                        account_number:  %payex.account_number%
                        encryption_key:  %payex.encryption_key%
                        sandbox: true
            storages:
                Acme\PayexBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PayexBundle\Model\AgreementDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: agreementRef
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true

        paypal_express_checkout_plus_cart:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_paypal_express_checkout
                    - other_examples.payum.action.status_details_aggregated_null_model

            storages:
                Acme\OtherExamplesBundle\Model\Cart:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaypalExpressCheckoutBundle\Model\PaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true
                        
        authorize_net_plus_cart:
            authorize_net_aim:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true
                actions:
                    - other_examples.payum.action.capture_cart_with_authorize_net
                    - other_examples.payum.action.status_details_aggregated_null_model

            storages:
                Acme\OtherExamplesBundle\Model\Cart:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\AuthorizeNetPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true

        paypal_express_checkout_via_jms_plugin:
            jms_payment_plugin: ~
            storages:
                JMS\Payment\CoreBundle\Entity\Payment:
                    doctrine:
                        driver: orm
                        payment_extension: true
                Acme\PaymentBundle\Model\TokenizedDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: token
                        payment_extension: true