_welcome:
    pattern:  /
    defaults: { _controller: AcmePaymentBundle:Default:index }
    
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    prefix:   /

acme_paypal_express_checkout:
    resource: "@AcmePaypalExpressCheckoutBundle/Resources/config/routing.yml"
    prefix:   /

acme_payment:
    resource: "@AcmePaymentBundle/Resources/config/routing.yml"
    prefix:   /
