rrrr_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_welcome:
    pattern:  /
    defaults: { _controller: AcmePaymentBundle:Default:index }
    
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    prefix:   /

acme_paypal_express_checkout:
    resource: "@AcmePaypalExpressCheckoutBundle/Resources/config/routing.yml"
    prefix:   /

acme_other_examples:
    resource: "@AcmeOtherExamplesBundle/Resources/config/routing.yml"
    prefix:   /

acme_payment:
    resource: "@AcmePaymentBundle/Resources/config/routing.yml"
    prefix:   /
